import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import Navbar from '@/components/nav/Navbar'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { Layout } from 'antd'
import Sidebar from '@/components/nav/Sidebar'
import { Content } from 'antd/es/layout/layout'

const inter = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <Layout>
            <Navbar />
            <Layout>
              <Sidebar />
              <Layout>
                <Content style={{ padding: '20px' }}>
                  <AntdRegistry>{children}</AntdRegistry>
                </Content>
              </Layout>
            </Layout>
          </Layout>
        </body>
      </UserProvider>
    </html>
  )
}
